### ISSUE TITLE
V2.1 released, v2.0 removed

### ISSUE THREAD

**Issue by barcharcraz** [mesonbuild/tinyply#2]
I’ll open a pr for 2.1 later today, but the archive for version 2.0 has been removed from upstream. Ive opened an issue upstream to request a comment on this, but I’m not sure how wraps should be handling this situation.

**Comment by sarum9in** [comment]
There is no special handling for this. We don't host source code for upstream either. It just means 2.0 wraps will be broken.

I pushed a `2.1` branch for you.
